### ISSUE TITLE
Update Documentation to explain how to use the search provider feature

### ISSUE THREAD

**Issue by adxsoft** [sethyuan/logseq-plugin-smartsearch#16]
Update Documentation to explain how to use the search provider feature

**Comment by sethyuan** [comment]
The search provider doesn't have all the features of the normal trigger, for example, it doesn't have tag completion. That's why I'm not promoting it in the documentation. The normal triggering method (ctrl+space by default) works on both editing and non-editing modes, it's interactive and has all the features Smart Search can offer, hence it's recommended.
